apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load-guaranteed
  name: load-guaranteed
spec:
  nodeName: gke-cluster-1-default-pool-6a8d6701-sf9f
  containers:
  - image: qarlm/ghz
    name: load
    args:
    - --insecure
    - --call
    - helloworld.Greeter.SayHello
    - -d
    - '{"name": "john"}'
    - --duration=5m
    - --concurrency=200
    - --qps=100
    - --duration-stop=wait
    - guaranteed:50051
  restartPolicy: Never

