apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load-burstable
  name: load-burstable
spec:
  nodeName: gke-cluster-1-default-pool-fea82791-t9zf
  containers:
  - image: qarlm/ghz
    name: load
    args:
    - --insecure
    - --call
    - helloworld.Greeter.SayHello
    - -d
    - '{"name": "john"}'
    - --duration=5m
    - --concurrency=200
    - --qps=100
    - --duration-stop=wait
    - burstable:50051
  restartPolicy: Never

