apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load-besteffort
  name: load-besteffort
spec:
  nodeName: gke-cluster-1-default-pool-fea82791-5brq
  containers:
  - image: qarlm/ghz
    name: load
    args:
    - --insecure
    - --call
    - helloworld.Greeter.SayHello
    - -d
    - '{"name": "john"}'
    - --duration=5m
    - --concurrency=200
    - --qps=100
    - --duration-stop=wait
    - besteffort:50051
  restartPolicy: Never

