apiVersion: v1
kind: Service
metadata:
  labels:
    app: besteffort
  name: besteffort
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app: besteffort

