apiVersion: v1
kind: Pod
metadata:
  labels:
    app: besteffort
  name: besteffort
spec:
  nodeName: gke-cluster-1-default-pool-fea82791-2jdj
  containers:
  - image: sckmkny/hello-threads-java:0.1.0
    name: workload
    ports:
    - name: grpc
      containerPort: 50051

