apiVersion: v1
kind: Pod
metadata:
  labels:
    app: burstable
  name: burstable
spec:
  nodeName: gke-cluster-1-default-pool-6a8d6701-vnl6
  containers:
  - image: sckmkny/hello-threads-java:0.1.0
    name: workload
    ports:
    - name: grpc
      containerPort: 50051
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
