apiVersion: v1
kind: Service
metadata:
  labels:
    app: burstable
  name: burstable
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app: burstable

