apiVersion: v1
kind: Service
metadata:
  labels:
    app: guaranteed
  name: guaranteed
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app: guaranteed

